#!/bin/bash
set -e


[ -e ../template/zfunctions.sh ] && source ../template/zfunctions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control lxde
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxde-settings.install \
    > ./debian/${CODENAME_SAFE}-lxde-settings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxde-settings.postinst \
    > ./debian/${CODENAME_SAFE}-lxde-settings.postinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxde-livesettings.install \
    > ./debian/${CODENAME_SAFE}-lxde-livesettings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxde-livesettings.lintian-overrides \
    > ./debian/${CODENAME_SAFE}-lxde-livesettings.lintian-overrides

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxde-livesettings.preinst \
    > ./debian/${CODENAME_SAFE}-lxde-livesettings.preinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-lxde-livesettings.service \
    > ./debian/${CODENAME_SAFE}-lxde-livesettings.service


## templating

[ -d ./etc ] && rm -rf ./etc
[ -d ./usr ] && rm -rf ./usr
[ -d ./lxterminal ] && rm -rf ./lxterminal
cp -a ../template/etc .
cp -a ../template/usr .
cp -a ../template/lxterminal .

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/etc/skel/config/pcmanfm/main.lxde \
    > ./etc/skel/config/pcmanfm/main.lxde


grub_template lxde


exit 0
