#!/bin/bash
set -e


source ./functions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control lxde
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
    ./debtemplate/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/get-template \
    > ./debian/get-template
chmod 755 ./debian/get-template


sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.install \
    > ./debian/${CODENAME_SAFE}-lxde-settings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.postinst \
    > ./debian/${CODENAME_SAFE}-lxde-settings.postinst


sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.install \
    > ./debian/${CODENAME_SAFE}-lxde-livesettings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.lintian-overrides \
    > ./debian/${CODENAME_SAFE}-lxde-livesettings.lintian-overrides

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.preinst \
    > ./debian/${CODENAME_SAFE}-lxde-livesettings.preinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.postinst \
    > ./debian/${CODENAME_SAFE}-lxde-livesettings.postinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.service \
    > ./debian/${CODENAME_SAFE}-lxde-livesettings.service


## templating

[ -d ./etc ] && rm -rf ./etc
[ -d ./usr ] && rm -rf ./usr
[ -d ./lxterminal ] && rm -rf ./lxterminal
cp -a templates/* .


sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    template/etc/skel/config/pcmanfm/main.lxde \
    > etc/skel/config/pcmanfm/main.lxde


grub_template lxde


exit 0
